### ISSUE TITLE
Only one icon is showing after VSCode update

### ISSUE THREAD

**Issue by MostHated** [iocave/customize-ui#41]
Hey there,  
After doing a VSCode update, only one icon is showing now and the rest are under the ellipsis menu.

![](https://i.imgur.com/ToLnkRm.png)

Thanks,
-MH

**Comment by knopp** [comment]
I pushed 0.1.36 that should fix this. Please let me know if it works for you. I also added option to hide the Account and Settings icons (customizeUI.activityBarHideSettings) because it's starting to get crowded.

**Comment by MostHated** [comment]
I tried to right-click and select "Install a different version" I don't see 0.1.36 available yet within VSCode, I am guessing it might take a bit for it to show? I have not installed an extension manually before, but I imagine I can just clone the repo and then place it in a folder somewhere?

**Comment by knopp** [comment]
It usually takes few minutes for new update to show. You can build it from source but it shouldn't take longer than 10 minutes.

**Comment by knopp** [comment]
Actually, I seem to have  problem pushing the extension. I didn't notice before but it failed.

**Comment by knopp** [comment]
Well, until that is resolved (doesn't seem like a problem on my side), here's the extension.

[customize-ui-0.1.36.vsix.zip](https://github.com/iocave/customize-ui/files/4578155/customize-ui-0.1.36.vsix.zip)

**Comment by MostHated** [comment]
It just updated on my end and everything is good. I am back in action. 👍  Much appreciated.

**Comment by MostHated** [comment]
Hey there, it looks like it's doing it again, unfortunately.

![](https://i.imgur.com/Ve4gll2.png)

**Comment by knopp** [comment]
I pushed 0.1.38. Please let me know if it works for you. In general it's not a great idea to use customize-ui with insiders, as microsoft likes to refactor stuff and sometimes customize ui needs few days to catch up :)

**Comment by MostHated** [comment]
I have checked several times but still don't see 1.38. I appreciate your prompt fixes, but I understand that it is probably a burden to try and keep up with Insiders, as you mentioned. I liked having things customized, but as you also mentioned it is probably not the best idea for a reliable interface. I will just disable it for the time being.

**Comment by knopp** [comment]
I'm not sure what's going on, VSCE is acting very weird lately. I published it again, let's see if it works.

**Comment by MostHated** [comment]
I updated it and enabled it, things are good again. 👍
